config/routes.rb
Rails.application.routes.draw do
  get 'errors/not_found'
  get 'errors/internal_server_error'
  devise_for :users
  root to: "pages#home"

  get "calendar", to: "pages#calendar"

  resources :pets do
    resources :events
  end
  resources :user_pet

  get "up" => "rails/health#show", as: :rails_health_check

  match "/404", to: "errors#not_found", via: :all
  match "/500", to: "errors#internal_server_error", via: :all
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :pet


  class Snippet
    CATEGORIES = ["Rendez-vous", "Traitement", "Loisir"]
  end
end

app/models/pet.rb
class Pet < ApplicationRecord


  SPECIES = ['Chien', 'Chat', 'Hamster', 'Souris', 'Cheval', 'Serpent', 'Oiseau', 'Poisson', 'Grenouille', 'Araignée',]


  has_many :user_pets, dependent: :destroy # donne la méthode @pet.user_pets
  has_many :users, through: :user_pets
  has_many :events, dependent: :destroy

  validates :name, presence: true
  validates :breed, presence: true
  validates :birth_date, presence: true
  validates :weight, presence: true
  validates :description, presence: true
  validates :animal_type, presence: true, inclusion: { in: SPECIES}

  has_one_attached :photo

  def age
    return nil unless birth_date

    now = Time.zone.now.to_date
    years = now.year - birth_date.year
    months = now.month - birth_date.month

    if months < 0
      years -= 1
      months += 12
    end

    "#{years} an#{'s' if years != 1} et #{months} mois"
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :user_pets, dependent: :destroy
  has_many :pets, through: :user_pets
  has_many :events, through: :pets
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/user_pet.rb
class UserPet < ApplicationRecord
  belongs_to :user
  belongs_to :pet
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  def default_url_options
    { host: ENV["DOMAIN"] || "localhost:3000" }
  end
end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController
  def not_found
    render status: 404
  end

  def internal_server_error
    render status: 500
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_pet

  def index
    @events = @pet.events
  end

  def show
    @event = Event.find(params[:id])
  end

  def new
    @event = @pet.events
    @event = Event.new
  end

  def create
    @event = @pet.events.new(event_params)
    if @event.save
      redirect_to pet_path(@pet), notice: 'Évènement créé avec succès'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @event = @pet.events.find(params[:id])
    @event.destroy
    redirect_to pet_path(@pet), notice: 'Évènement supprimé avec succès'
  end

  private

  def set_pet
    @pet = Pet.find(params[:pet_id])
  rescue ActiveRecord::RecordNotFound
    redirect_to pets_path, alert: "Pet not found."
  end

  def event_params
    params.require(:event).permit(:title, :treatment_type, :details, :start, :end)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
  end

  def calendar
    @events = current_user.events
    @upcoming_events = @events.where("start <= ?", Date.today + 3).where("start >= ?", Date.today).order(start: :asc)
  end
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  before_action :upcoming_events

  def index
    @pets = current_user.pets
  end

  def show
    @pet = Pet.find(params[:id])
    @events = @pet.events
    @upcoming_events_of_pet = @pet.events.where("start <= ?", Date.today + 3).where("start >= ?", Date.today).order(start: :asc)
  end

  def new
    @pet = Pet.new
    @step = params[:step].to_i
    unless params[:pet].nil?
      @pet = Pet.new(pet_params)
    end
  end

  def create
    @pet = Pet.new(pet_params)
    @user_pet = UserPet.new(user: current_user, pet: @pet)
    if @pet.save && @user_pet.save
      redirect_to pets_path, notice: 'Le compagnon a été créé avec succès'
    else
      # 1 j'assigne dans une variable step la valeur de la step
      step = define_step(@pet.errors.messages)
      # 2 je renvoie cette valeur dans les paramètres que je retourne
      redirect_to new_pet_path({ pet: pet_params }.merge(step: step))
    end
  end

  def edit
    @pet = Pet.find(params[:id])
  end

  def update
    @pet = Pet.find(params[:id])
    if @pet.update(pet_params)
      redirect_to pet_path(@pet), notice: 'Le compagnon a été modifié avec succès.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @pet = Pet.find(params[:id])
    @pet.destroy
    respond_to do |format|
      format.html { redirect_to pets_path, status: :see_other, notice: 'Le compagnon a été retiré' }
      format.text { "ok" }
    end
  end

  private

  def pet_params
    params.require(:pet).permit(:name, :breed, :animal_type, :birth_date, :weight, :description, :photo)
  end

  def upcoming_events
    @upcoming_events = current_user.events.where("start <= ?", Date.today + 3).where("start >= ?", Date.today).order(start: :asc)
  end

  def define_step(errors)
    if errors.key?(:name)
      return 0
    elsif errors.key?(:animal_type)
      return 1
    elsif errors.key?(:breed)
      return 2
    elsif errors.key?(:birth_date) || errors.key?(:weight)
      return 3
    elsif errors.key?(:description)
      return 4
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
   content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/events/_create-event-form.html.erb
<div class="container">
  <h1>Créer un évenement</h1>
  <%= simple_form_for [@pet, Event.new], data: { controller: "toggle-for-form", toggle_for_form_show_if_value: "Traitement", toggle_for_form_show_recurrence_if_value: "Loisir" } do |f| %>
    <div data-toggle-for-form-target="title">
      <%= f.input :title,
                as: :radio_buttons,
                collection_wrapper_tag: 'div',
                collection_wrapper_class: 'title-wrapper',
                item_wrapper_class: 'title-item',
                input_html: { class: 'title-selector', data: { action: 'change->toggle-for-form#toggleField' } },
                collection: ["Rendez-vous", "Traitement", "Loisir"],
                label_wrapper_tag: 'div',
                label_wrapper_class: 'label-wrapper',
                label: ('<i class="fa-solid fa-font-awesome fa-lg position-flag" style="color: #48ADA9;"></i>').html_safe %>
    </div>

    <div data-toggle-for-form-target="treatmentInput" class="hidden">
      <%= f.input :treatment_type, placeholder: "Type de traitement", input_html: { class: 'form-input' }, label: ('<i class="fa-solid fa-syringe fa-lg" style="color: #48ADA9;"></i>').html_safe %>
    </div>

    <%# <div data-toggle-for-form-target="recurrenceInput" class="hidden">
      <%= f.input :recurrence, placeholder: "Récurrence", input_html: { class: 'form-input' }, label: ('<i class="fa-solid fa-arrow-rotate-right fa-lg" style="color: #48ADA9;"></i>').html_safe %>
      <%# </div> %>

    <%= f.input :start, as: :string, input_html: { data: { controller: "datepicker" } }, label: ('<i class="fa-solid fa-circle-play fa-lg" style="color: #48ADA9;"></i>').html_safe %>

    <%= f.input :end, as: :string, input_html: { data: { controller: "datepicker" } }, label: ('<i class="fa-solid fa-circle-stop fa-lg" style="color: #48ADA9;"></i>').html_safe %>

    <%= f.input :details, placeholder: "Détails", input_html: { class: 'form-input' }, label: ('<i class="fa-solid fa-circle-info fa-lg" style="color: #48ADA9;"></i>').html_safe %>

    <div class="button-center">
      <%= f.button :submit, "Enregistrer", class: 'green-basic-btn' %>
    </div>
  <% end %>
</div>

app/views/events/index.html.erb
<div data-controller="fullcalendar" 
    data-fullcalendar-event-value='<%= @events.to_json %>'>
</div>

app/views/events/new.html.erb
<%= render "create-event-form" %>

app/views/events/show.html.erb
<h1> <%= @event.title %> </h1>

<h3> Le <%= @event.start %> </h3>

<p> <%= @event.details %> </p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= meta_title %></title>
    <meta name="description" content="<%= meta_description %>">

    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= meta_image %>" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link rel="preload" href="<%= asset_path('application.css') %>" as="style">
    <%= stylesheet_link_tag "application", media: "all" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/sweetalert2@11/dist/sweetalert2.min.css">
    <%= favicon_link_tag 'fav32.png' %>
    <link rel="apple-touch-icon" sizes="57x57" href="<%= asset_path('apple-icon-57x57.png') %>">
    <link rel="apple-touch-icon" sizes="60x60" href="<%= asset_path('apple-icon-60x60.png') %>">
    <link rel="apple-touch-icon" sizes="72x72" href="<%= asset_path('apple-icon-72x72.png') %>">
    <link rel="apple-touch-icon" sizes="76x76" href="<%= asset_path('apple-icon-76x76.png') %>">
    <link rel="apple-touch-icon" sizes="114x114" href="<%= asset_path('apple-icon-114x114.png') %>">
    <link rel="apple-touch-icon" sizes="120x120" href="<%= asset_path('apple-icon-120x120.png') %>">
    <link rel="apple-touch-icon" sizes="144x144" href="<%= asset_path('apple-icon-144x144.png') %>">
    <link rel="apple-touch-icon" sizes="152x152" href="<%= asset_path('apple-icon-152x152.png') %>">
    <link rel="apple-touch-icon" sizes="180x180" href="<%= asset_path('apple-icon-180x180.png') %>">
    <link rel="icon" type="image/png" sizes="192x192" href="<%= asset_path('android-icon-192x192.png') %>">
    <link rel="icon" type="image/png" sizes="32x32" href="<%= asset_path('favicon-32x32.png') %>">
    <link rel="icon" type="image/png" sizes="96x96" href="<%= asset_path('favicon-96x96.png') %>">
    <link rel="icon" type="image/png" sizes="16x16" href="<%= asset_path('favicon-16x16.png') %>">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="/ms-icon-144x144.png">
    <meta name="theme-color" content="#ffffff">
  </head>
  <body class="body-container <%= 'full-page' if controller_name == 'pages' && action_name == 'home' %>">
    <%= render "shared/flashes" %>
    <% unless controller_name == "pages" %>
      <%= render 'shared/navbar' %>
    <% end %>
    <%= yield %>
    <% unless controller_name == "pages" %>
      <%= render 'shared/footer' %>
    <% end %>
  </body>
</html>

app/views/pages/calendar.html.erb
<%= render "shared/navbar" %>
<h1> Calendrier de mes animaux </h1>
<div class="container">
  <div data-controller="fullcalendar"
      data-fullcalendar-event-value='<%= @events.to_json %>'>
  </div>

  <div class="container mt-4 w-100 p-0 m-0">
      <% @events.each do |event| %>
          <div class="modal fade" id="<%= event.id %>" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
              <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable">
                  <div class="modal-content">
                      <div class="modal-header">
                          <h1 class="modal-title fs-5" id="exampleModalLabel"><%= event.title %> pour <%= event.pet.name %></h1>
                          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                      </div>
                      <div class="modal-body">
                          <%= event.details %>
                      </div>
                      <div class="modal-footer">
                          <button type="button" style="border: none">
                              <%= link_to pet_event_path(event.pet, event), data: { turbo_method: :delete } do %>
                                  <i class="fa-solid fa-trash fa-lg" style="color: #48ADA9;"></i>
                              <% end %>
                          </button>
                      </div>
                  </div>
              </div>
          </div>
      <% end %>
  </div>
</div>
<%= render "shared/footer" %>

app/views/pets/_form.html.erb
    <div class="container">
  <%= simple_form_for @pet do |f| %>
    <%= f.input :name, label: "Nom", :input_html => { :class => 'form-input' } %>
    <%= f.input :animal_type, collection: Pet::SPECIES, label: " Type de compagnon ", :input_html => { :class => 'form-input' } %>
    <%= f.input :breed, label: "Race", :input_html => { :class => 'form-input' } %>
    <%= f.input :birth_date, as: :date, start_year: Date.today.year - 20, end_year: Date.today.year, label: "Date de naissance", :input_html => { :class => 'form-input' } %>
    <%= f.input :weight, label: "Poids", :input_html => { :class => 'form-input' } %>
    <%= f.input :description, label: "Description", :input_html => { :class => 'form-input' } %>
    <%= f.input :photo, as: :file , :input_html => { :class => 'form-input' } %>
    <%= f.button :submit, "Enregistrer", class: 'green-basic-btn' %>
  <% end %>
</div>

app/views/pets/index.html.erb
<%= render "shared/footer" %>
<div class="container">
  <ul>
    <% @upcoming_events.each do |event| %>
      <% if Date.today == event.start %>
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
          Attention, n'oubliez pas votre évènement ce jour pour <strong><%= event.pet.name %></strong> : <%= link_to event.title, pet_event_path(event.pet, event) %>
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
          </button>
        </div>
      <% end %>
    <% end %>
  </ul>
</div>

<div class="my-pets-container">
  <%= render "shared/mini_card" %>
</div>

app/views/pets/show.html.erb
<div class="container">

  <%= render "shared/card" %>
 
  <ul>
    <% @upcoming_events_of_pet.each do |event| %>
      <% if Date.today == event.start %>
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
          Attention, n'oubliez pas votre évènement ce jour : <%= event.title %>
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
          </button>
        </div>
      <% elsif Date.today + 1 == event.start %>
        <div class="alert alert-info alert-dismissible fade show" role="alert">
          Evenement prévu pour demain : <%= event.title %>
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
          </button>
        </div>
      <% elsif Date.today + 2 == event.start || Date.today + 3 == event.start %>
        <div class="alert alert-info alert-dismissible fade show" role="alert">
          Evenement prévu dans les 3 prochains jours : <%= event.title %> le <%= event.start %>
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
          </button>
        </div>
      <% end %>
    <% end %>
  </ul>

  <div data-controller="fullcalendar"
      data-fullcalendar-event-value='<%= @events.to_json %>'>
  </div>

  <div class="container mt-4 w-100 p-0 m-0">
    <% @events.each do |event| %>
      <div class="modal fade" id="<%= event.id %>" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable">
          <div class="modal-content">
            <div class="modal-header">
              <h1 class="modal-title fs-5" id="exampleModalLabel">
                <% if event.title == "Traitement" %>
                  <%= event.treatment_type %>
                <% else %>
                  <%= event.title %>
                <% end %>
              </h1>
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
              <%= event.details %>
            </div>
            <div class="modal-footer">
              <button type="button" style="border: none">
                <%= link_to pet_event_path(@pet, event), data: { turbo_method: :delete } do %>
                  <i class="fa-solid fa-trash fa-lg" style="color: #48ADA9;"></i>
                <% end %>
              </button>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_cardnonused.html.erb
<%# il s'agit du code des card utiliser dans l'index.html.erb a voir ce qu'on en fait  %>


<div class="my-pets-container">
  <h1> Mes compagnons </h1>

  <% @pet.each do |list| %>
    <div class="card-container">

      <!-- Infos de l'animal -->

      <% if pet.photo.key == nil %>
        <%= image_tag "lumo.png", width: "250px", height: "250px", alt: "Petit chat mignon", style: "border-radius: 50%;" %>
      <% else %>
        <%= cl_image_tag pet.photo.key, width: "250px", height: "250px", alt: "Petit chat mignon", style: "border-radius: 50%;", class: "card-image" %>
      <% end %>
      <h2><%= list.pet.name %></h2>
      <div class="pet-infos-container">

          <p><i class="fa-solid fa-weight-hanging" style="color: #060d0e;"></i> <%= list.pet.weight %>kg</p>
          <p><i class="fa-solid fa-cake-candles" style="color: #060d0e;"></i> <%= list.pet.age %></p>
          <p>
            <% if list.pet.animal_type == "Chat" %>
              <i class="fa-solid fa-cat" style="color: #060d0e;"></i>
            <% elsif list.pet.animal_type == "Chien" %>
              <i class="fa-solid fa-dog" style="color: #060d0e;"></i>
            <% elsif list.pet.animal_type == "Oiseau" %>
              <i class="fa-solid fa-crow" style="color: #060d0e;"></i>
            <% elsif list.pet.animal_type == "Cheval" %>
              <i class="fa-solid fa-horse" style="color: #060d0e;"></i>
            <% elsif list.pet.animal_type == "Poisson" %>
              <i class="fa-solid fa-fish" style="color: #060d0e;"></i>
            <% elsif list.pet.animal_type == "Grenouille" %>
              <i class="fa-solid fa-frog" style="color: #060d0e;"></i>
            <% elsif list.pet.animal_type == "Araignée" %>
              <i class="fa-solid fa-spider" style="color: #060d0e;"></i>
            <% elsif list.pet.animal_type == "Serpent" %>
              <i class="fa-solid fa-worm" style="color: #060d0e;"></i>
            <% elsif list.pet.animal_type == "Insecte" %>
              <i class="fa-solid fa-locust" style="color: #060d0e;"></i>
            <% elsif list.pet.animal_type == "Dragon" %>
              <i class="fa-solid fa-dragon" style="color: #060d0e;"></i>
            <% else %>
              <i class="fa-solid fa-shrimp" style="color: #060d0e;"></i>
            <% end %>
            <%= list.pet.breed %>
      </p>
      </div>
      <p><%= list.pet.description %></p>

      <!-- Boutons action pour agir sur mes animaux-->
      <div class="pet-actions-display-controller" data-controller="pet-action-display">
        <div class="pet-actions">

          <i class="fa-solid fa-pencil fa-xl" style="color: #48ADA9;" data-action="click->pet-action-display#toggleModification"></i>
          <i class="fa-solid fa-chevron-down fa-2xl" style="color: #48ADA9;" data-action="click->pet-action-display#toggleInformations"></i>
          <%# link_to raw('<i class="fa-solid fa-eraser fa-xl" style="color: #48ADA9;"></i>'), pet_path(list.pet.id), data: { turbo_method: :delete, turbo_confirm: "Êtes vous sûr(e)?" } %>
          <i class="fa-solid fa-plus fa-2xl" style="color: #48ADA9;" data-action="click->pet-action-display#toggleAddEvent"></i>

          <%# link_to raw('<i class="fa-solid fa-chevron-down fa-2xl" style="color: #48ADA9;"></i>'), pet_path(list.pet.id) %>
          <%# link_to raw('<i class="fa-solid fa-pencil fa-xl" style="color: #48ADA9;"></i>'), pets_path %>
        </div>

        <!-- divs pour le contenu (activées lors du click sur les boutons correspondants) -->

        <div class="card-pet-modification" data-pet-action-display-target="petModificationContainer">
          <p>Modification de la fiche de <%= list.pet.name %></p>
          <%= link_to "modifier", pets_path, class: "btn btn-secondary"%>
        </div>

        <div class="card-pet-informations" data-pet-action-display-target="petInformationsContainer">
          <p>Informations sur <%= list.pet.name %></p>
          <%= link_to "voir la fiche", pet_path(list.pet.id), class: "btn btn-secondary"%>
        </div>

        <div class="card-pet-add-event" data-pet-action-display-target="petAddEventContainer">
          <p>Ajout d'évènement pour <%= list.pet.name %></p>
          <%= link_to "créer un évenement", new_pet_event_path(list.pet.id), class: "btn btn-secondary"%>
        </div>

      </div>

    </div>
  <% end %>

app/views/shared/_footer.html.erb
<% if current_user != nil %>
  <div class="offcanvas offcanvas-bottom footer-offcanvas-style" tabindex="-1" id="offcanvasFooterSearch" aria-labelledby="offcanvasBottomLabel">
    <div class="offcanvas-header">
      <div class="titre-et-bouton">
        <h5 class="offcanvas-title" id="offcanvasBottomLabel">Rechercher</h5>
        <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close" data-action="click->highlight-footer#highlightLink"></button>
      </div>
      <div class="grid-container-search">
        <% current_user.pets.each do |pet| %>
          <%= link_to pet_path(pet) do %>
            <div class="grid-avatar-search">
              <% if pet.photo.key == nil %>
               <% if pet.photo_url == nil %>
                 <%= image_tag "logo-white.png", class: "mini-avatar-search" %>
               <% else %>
                 <%= image_tag pet.photo_url, class: "mini-avatar-search" %>
               <% end %>
              <% else %>
               <%= cl_image_tag pet.photo.key, class: "mini-avatar-search" %>
              <% end %>
             </div>
             <% end %>
            <% end %>
         </div>
    </div>
  </div>
  <div class="offcanvas offcanvas-bottom footer-offcanvas-style" tabindex="-1" id="offcanvasFooterProfile" aria-labelledby="offcanvasBottomLabel">
    <div class="offcanvas-header">
      <h5 class="offcanvas-title" id="offcanvasBottomLabel">Mon profil</h5>
      <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close" data-action="click->highlight-footer#highlightLink"></button>
      <div class="offcanvas-content-style">
        <%= link_to "Log out", destroy_user_session_path, class:'btn red-basic-btn', data: {turbo_method: :delete} %>
      </div>
    </div>
  </div>

<footer class="phone-footer" data-controller="highlight-footer">
  <%= link_to pets_path, class: "icon-link home-icon" do %>
    <i class="fa-solid fa-house fa-lg"></i>
    <span class="indicator"></span>
  <% end %>

  <div class="icon-link profile-icon" data-highlight-footer-target="search" data-action="click->highlight-footer#highlightSearchLink" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasFooterSearch" aria-controls="offcanvasBottom">
    <i class="fa-solid fa-magnifying-glass fa-lg"></i>
    <span class="indicator"></span>
  </div>

  <%= link_to calendar_path, class: "icon-link services-icon" do %>
    <i class="fa-solid fa-calendar fa-lg"></i>
    <span class="indicator"></span>
  <% end %>

  <div class="icon-link profile-icon" data-highlight-footer-target="profile" data-action="click->highlight-footer#highlightProfileLink" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasFooterProfile" aria-controls="offcanvasBottom">
    <i class="fa-solid fa-user fa-lg"></i>
    <span class="indicator"></span>
  </div>
</footer>
<% end %>

app/views/shared/_navbar.html.erb
  <div class="navbar-container" data-controller="navbar-notifications">
    <div class="petsies-navbar">
        <%= link_to pets_path do %>
          <%= image_tag "logo-white.png", class: "navbar-logo" %>
        <% end %>
        <% if current_user != nil %>
          <div data-action="click->navbar-notifications#toggle" data-navbar-notifications-target="toggleButton" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNotifications" aria-controls="offcanvasTop">
            <i class="fa-solid fa-bell fa-xl fa-rotate-by" style="color: #fffbf4; --fa-rotate-angle: 25deg;"></i>
          </div>
          <% if @upcoming_events.nil? %>
            <div class="notifications-number-alert hide-notifications"></div>
          <% else %>
            <div class="notifications-number-alert" data-action="click->navbar-notifications#toggle" data-navbar-notifications-target="toggleNumberButton" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNotifications" aria-controls="offcanvasTop"><span><%= @upcoming_events.count %></span></div>
          <% end %>

    </div>
        <div class="offcanvas offcanvas-top" tabindex="-1" id="offcanvasNotifications" aria-labelledby="offcanvasTopLabel">
          <div class="offcanvas-header">
              <h5 id="offcanvasTopLabel">Offcanvas top</h5>
              <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
          </div>
          <div class="offcanvas-body">

            <ul style="list-style:none;" class="notifications-list">
              <% if @upcoming_events.nil? && @pet%>
                <li class="notifications-list">Aucun évènement à venir pour <%= @pet.name %></li>
              <% else %>
                <% @upcoming_events.each do |event| %>
                  <% if Date.today == event.start || Date.today > (event.start - 4) || Date.today < (event.start + 1) %>
                    <li>
                      <i class="fa-solid fa-lg fa-circle-exclamation" style="color: #FFFBF4;"></i> &nbsp; <strong><%= link_to event.title, pet_event_path(event.pet, event), style: "text-decoration:none; color:#FFFBF4" %></strong> pour <strong><%= event.pet.name %></strong> le <strong><%= event.start.to_s.gsub('-', '/') %></strong>
                    </li>
                  <% end %>
                <% end %>
              <% end %>
            </ul>

          </div>
        </div>
      <% end %>
    </div>